services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - prometheus

  fn-local-exporter-api:
    image: euiyoung/go-exporter-api:es
    container_name: go-exporter-api
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - 2100:2112
    volumes:
      - ./:/app/FN-Go-Exporter-Services
    restart: unless-stopped
    environment:
      #- ES_HOST=http://host.docker.internal:9203
    networks:
      - bridge

networks:
  monitoring:
    driver: bridge