global:
  scrape_interval: 15s

# Alertmanager Configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['localhost:9093']

# loading at once and evaluate the rule periodically based on 'evaluation_interval'
# rule_files:
# - "./alert-rule.yml"

scrape_configs:
  - job_name: 'myapp'
    scrape_interval: 10s
    static_configs:
    - targets:
      - 'host.docker.internal:2112/metrics' # or container-name:2112
  
  - job_name: myagent
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
    - targets:
      - host.docker.internal:2112
