server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./tmp/positions.yaml

clients:
  - url: http://모니터링서버ip:3100/loki/api/v1/push

scrape_configs:
- job_name: was1
  static_configs:
  - targets:
      - localhost
    labels:
      job: was1_app
      __path__: /home/bkwinners/MARU_APP/logs/root.txt
  - targets:
      - localhost
    labels:
      job: was1_pay
      __path__: /home/bkwinners/MARU_PAY/logs/root.txt