server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./tmp/positions.yaml

clients:
  - url: http://모니터링서버ip:3100/loki/api/v1/push

scrape_configs:
  - job_name: info
    static_configs:
      - targets:
          - localhost
        labels:
          job: test_info_logs
          __path__: /logs/*/info-*.log
  - job_name: warn
    static_configs:
      - targets:
          - localhost
        labels:
          job: test_warn_logs
          __path__: /logs/*/warn-*.log
  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: test_error_logs
          __path__: /logs/*/error-*.log