{
 "title": "[ES_Admin] Golang_Node_Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Quick Prometheus Node Service Monitoring [Dev]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "[Dev] Node CPU Usage",
   "type": "timeseries",
   "description": "CPU usage in the last 5 minutes",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpuUsage{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}"
    }
   ]
  },
  {
   "title": "[Dev] Node Memory Usage",
   "type": "timeseries",
   "description": "Memory usage in the last 5 minutes",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "basicMemoryUsedPercentGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}"
    }
   ]
  },
  {
   "title": "Quick Prometheus Node Service Monitoring [QA]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "[new QA-13] NodeCPU Usage",
   "type": "timeseries",
   "description": "CPU usage in the last 5 minutes",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpuUsage{server_job=~\"localhost03928|localhost03929|localhost93930\"}"
    }
   ]
  },
  {
   "title": "[new QA-13] Node Memory Usage",
   "type": "timeseries",
   "description": "Memory usage in the last 5 minutes",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "basicMemoryUsedPercentGauge{server_job=~\"localhost03928|localhost03929|localhost93930\"}"
    }
   ]
  },
  {
   "title": "Prometheus Node Services Monitoring [Dev]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpuUsage{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}",
     "legendFormat": "{{topic}}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "basicMemoryUsedPercentGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}",
     "legendFormat": "{{topic}}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Description",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "basiccpuModelInfoGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}"
    }
   ]
  },
  {
   "title": "Memory Description",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "basicMemoryInfoGBGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}"
    }
   ]
  },
  {
   "title": "Current Disk Usage (30's Refresh)",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "diskUsageGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1|localhost1|localhost1|localhost1\"}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(networkRxInfoGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1\"}[$__rate_interval])",
     "legendFormat": "{{name}}: sent "
    },
    {
     "expr": "-irate(networkTxInfoGauge{server_job=~\"localhost1|localhost1|localhost3|localhost1\"}[$__rate_interval])",
     "legendFormat": "{{name}}: received"
    }
   ]
  },
  {
   "title": "Prometheus Node Services Monitoring [QA13_NEW_ELK_v8]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpuUsage{server_job=~\"localhost03928|localhost03929|localhost03930\"}",
       "legendFormat": "{{topic}}",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "basicMemoryUsedPercentGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}",
       "legendFormat": "{{topic}}",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "CPU Description",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "basiccpuModelInfoGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}"
      }
     ]
    },
    {
     "title": "Memory Description",
     "type": "table",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "basicMemoryInfoGBGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}"
      }
     ]
    },
    {
     "title": "Current Disk Usage (30's Refresh)",
     "type": "table",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "diskUsageGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}"
      }
     ]
    },
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(networkRxInfoGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}[$__rate_interval])",
       "legendFormat": "{{name}}: sent "
      },
      {
       "expr": "-irate(networkTxInfoGauge{server_job=~\"localhost03928|localhost03929|localhost03930\"}[$__rate_interval])",
       "legendFormat": "{{name}}: received"
      }
     ]
    }
   ]
  }
 ]
}