# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x0c\x44\x42SQLRequest\x12\x0e\n\x06\x64\x62_url\x18\x01 \x01(\t\x12\x0b\n\x03sql\x18\x02 \x01(\t\"Z\n\x07\x45lement\x12\x13\n\x0bPROCESSNAME\x18\x01 \x01(\t\x12\x0e\n\x06STATUS\x18\x02 \x01(\t\x12\r\n\x05\x41\x44\x44TS\x18\x03 \x01(\t\x12\r\n\x05\x43OUNT\x18\x04 \x01(\x05\x12\x0c\n\x04\x44\x42ID\x18\x05 \x01(\t\"*\n\rDBSQLResponse\x12\x19\n\x07records\x18\x01 \x03(\x0b\x32\x08.Element\"#\n\x14MetricsStatusRequest\x12\x0b\n\x03\x65nv\x18\x01 \x01(\t\"A\n\x15MetricsStatusResponse\x12(\n\x07metrics\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2k\n\x0c\x44\x42Interfacer\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12\x31\n\x10GetMetricsStatus\x12\r.DBSQLRequest\x1a\x0e.DBSQLResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=47
  _globals['_HELLOREQUEST']._serialized_end=75
  _globals['_HELLOREPLY']._serialized_start=77
  _globals['_HELLOREPLY']._serialized_end=106
  _globals['_DBSQLREQUEST']._serialized_start=108
  _globals['_DBSQLREQUEST']._serialized_end=151
  _globals['_ELEMENT']._serialized_start=153
  _globals['_ELEMENT']._serialized_end=243
  _globals['_DBSQLRESPONSE']._serialized_start=245
  _globals['_DBSQLRESPONSE']._serialized_end=287
  _globals['_METRICSSTATUSREQUEST']._serialized_start=289
  _globals['_METRICSSTATUSREQUEST']._serialized_end=324
  _globals['_METRICSSTATUSRESPONSE']._serialized_start=326
  _globals['_METRICSSTATUSRESPONSE']._serialized_end=391
  _globals['_DBINTERFACER']._serialized_start=393
  _globals['_DBINTERFACER']._serialized_end=500
# @@protoc_insertion_point(module_scope)
